### ISSUE TITLE
Front end global style sheet

### ISSUE THREAD

**Issue by jyaneshseeam** [UPEI-Android/group-project-mindjogg#135]
## Context

In order to have the same feel throughout the whole app a global style sheet is needed

## Problem 
We don't have style sheet yet and inline style are being used ineach component
## Solution 

- [x] Create stylesheet
- [x] convert figma CSS to code inside of stylesheet

**Comment by sontushkpaul** [comment]
@jyaneshseeam Can you please prioritize the issue ?

**Comment by jyaneshseeam** [comment]
Yes, doing it right now

**Comment by sontushkpaul** [comment]
> Yes, doing it right now

Thank you
