### ISSUE TITLE
Mood history screen

### ISSUE THREAD

**Issue by sontushkpaul** [UPEI-Android/group-project-mindjogg#182]
## Context
User may want to see their mood history

## Problem 
There is no mood history screen

## solution 

- [x] Create a graph with daily or weekly mood summary 
- [x] Create list of mood for last week.

**Comment by jyaneshseeam** [comment]
@sontushkpaul  how is this issue going on, I was thinking, once user signs up if This pop up could be saying "Please check the verification email sent"
