### ISSUE TITLE
Show users' info in Edit Profile Screen

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#228]
## Context
The edit profile shows placeholder values (Steve Jobs) for the user. Now that the user info is served from the backend, we can replace this placeholder

## Problem
It should show the user's actual name, username, and profile pic

## Solution
Populate it with the userInfo from the backend

**Comment by jyaneshseeam** [comment]
@ja-chisholm  i replaced the name and user name already in my new pr , just need to pull profile pic now after I implement the profile pic upload backend

**Comment by ja-chisholm** [comment]
> @ja-chisholm i replaced the name and user name already in my new pr , just need to pull profile pic now after I implement the profile pic upload backend

Ah awesome! The edit profile screen shows the users' info + picture as well so it needs to be changed too - I can take care of that if you want, or you can

**Comment by jyaneshseeam** [comment]
> > @ja-chisholm i replaced the name and user name already in my new pr , just need to pull profile pic now after I implement the profile pic upload backend
> 
> Ah awesome! The edit profile screen shows the users' info + picture as well so it needs to be changed too - I can take care of that if you want, or you can

Actually I showed the name and the username on the drawer content js , you can just copy and paste the same code on the edit profile screen too, you can take care of it for the picture too
