### ISSUE TITLE
Dockerize the client

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#23]
## Context 
The app should be dockerized

## Problem 
Right now, the app's dependencies are not universal across systems. Dockerizing the app should fix this.

## Solution: 
- [ ] Launch a docker machine
- [ ] Create a Dockerfile in the client/mindjogg folder
- [ ] Create a Docker image from that Dockerfile
- [ ] Run the app in the container created by that Docker image

https://www.docker.com/

**Comment by sontushkpaul** [comment]
We will not dockerize the client
