### ISSUE TITLE
Create a checklist for testing

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#236]
##Context
We have a good amount of automated tests, but we should go through and manually test functionality

##Problem
We should make a checklist to standardize what tests should be run. Stuff like trying negatives, positives, and zeros in integer inputs, clicking every button, etc

##Solution
Make this checklist so we can be sure that everything is tested

**Comment by DemiAdisa** [comment]
This issue has been completed yeah?

**Comment by ja-chisholm** [comment]
> This issue has been completed yeah?

Yes, I'll close it
