### ISSUE TITLE
Determine components required for frontend

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#42]
## Context
Before we can make any components, we need a list of the components required for the frontend

## Problem
We only have a rough idea of what components we'll need

## Solution
For each page the Figma prototype:
- [ ] Determine what components (text box, web form, button, etc) will be needed
- [ ] Add these components to a master list
Once that list is finished:
- [ ] Create an issue for each component

**Comment by sontushkpaul** [comment]
@ja-chisholm Please document your research in GitHub. You can create a research folder in GitHub. It can be outside app folder.
