### ISSUE TITLE
Emergency Support Resources: Create UI Mockup

### ISSUE THREAD

**Issue by DemiAdisa** [UPEI-Android/group-project-mindjogg#47]
## Context
After finding and storing the information we find on emergency support, we need to create an interface that allows the user to access it on Figma to get an idea of how it will look.

## Problem
We need a UI to access the information.

## Solution
- [x] Create a Figma page that has a button for each of the information we find

**Comment by DemiAdisa** [comment]
A mockup has been created on Figma, please go to this [link](https://www.figma.com/file/3714aYKYor5Sll85z8yuqm/MindjoggUI?node-id=131%3A168) and review it. Thank you

**Comment by jyaneshseeam** [comment]
Looks good @DemiAdisa

**Comment by DemiAdisa** [comment]
Great, when another person agrees, you can go ahead and close the issue 👌
