### ISSUE TITLE
Create React-Native Screen: Landing Page

### ISSUE THREAD

**Issue by DemiAdisa** [UPEI-Android/group-project-mindjogg#48]
## Context
So we got an idea for our landing page for the app but now we have to implement the React-Native code.

## Problem
We need to implement the React Native Screen

## Solution
- [ ] Implement React Native Screen
- [ ] Decide what components the screen will need ( "Get Started" Button and Logo for this page)
- [ ] Implement the components in the screen
- [ ] Ensure it appears on screen

**Comment by DemiAdisa** [comment]
Blocked by #42

**Comment by ja-chisholm** [comment]
closed by #150
