### ISSUE TITLE
Edit Profile functionality: Design UI  

### ISSUE THREAD

**Issue by sontushkpaul** [UPEI-Android/group-project-mindjogg#53]
## Context 
We need to provide the edit their profile after their registration is done. It is important because we are taking minimal information about the user while registering the user.

## Problem 
We do not have the UI design for the form where the user can edit their profile information. 

## Solution 

- [x] Find what information about the user needs to be stored 
- [x] Design a form for editing the information using Figma 
- [x] Submit for peer review 

A mockup has been created on Figma, please go to this [link](https://www.figma.com/proto/3714aYKYor5Sll85z8yuqm/MindjoggUI?node-id=2%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2&show-proto-sidebar=1) and review it. Thank you

**Comment by jyaneshseeam** [comment]
A mockup has been created on Figma, please go to this [link](https://www.figma.com/proto/3714aYKYor5Sll85z8yuqm/MindjoggUI?node-id=2%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2&show-proto-sidebar=1) and review it. Thank you

@DemiAdisa @sontushkpaul  @ja-chisholm

**Comment by DemiAdisa** [comment]
Just took a look, the mockup looks standard! Good job 👌

**Comment by jyaneshseeam** [comment]
Since everyone reviewed it during the spring retrospective meeting, its being closed now
