### ISSUE TITLE
Determine a single code style and add it to ESLint rules

### ISSUE THREAD

**Issue by jyaneshseeam** [UPEI-Android/group-project-mindjogg#59]
## Context
It is essential that all developers on the team have a similar code style so that each other understands code written easily.

## Problem
Different styles might be difficult to understand at first

## Solution
- [x] Add Eslint rules
- [x] Update them in wiki

**Comment by ja-chisholm** [comment]
Rules are [on the wiki](https://github.com/UPEI-Android/group-project-mindjogg/wiki/Coding-Standards), so this issue will just involve updating ESLint's rules
