### ISSUE TITLE
Add stack navigation

### ISSUE THREAD

**Issue by jyaneshseeam** [UPEI-Android/group-project-mindjogg#62]
## Context

Navigation is a very important aspect of mobile application development.

## Problem

There are some libraries for navigations available already but needs to be implemented

## Solution
- [x] Install React Navigation stack
- [x] Create Necessary Screen for each mini app
- [x] Create Stack Navigator for each mini app

**Comment by ja-chisholm** [comment]
@jyaneshseeam what is this blocked by?

**Comment by jyaneshseeam** [comment]
> 
By issue #60 , I could be wrong as this could be developed then restructured later.
