### ISSUE TITLE
Create  Initial UI Design of the App 

### ISSUE THREAD

**Issue by sontushkpaul** [UPEI-Android/group-project-mindjogg#9]
## Context
To make implementation easy, the initial design of app should be done.

## Problem 
A Figma Design for the front app is needed. The design will guide the frontend developer to build the UI screens and components of the app.

## Solution 

- [x] Create a Figma Account 
- [x] Choose a Primary, a Secondary and Background Color for the app
- [x] Design UI for Welcome Screen with MindJogg Logo (Not created yet)
- [x] Design logo
- [x] Design Sign Up Screen
- [x] Design Sign In Screen
- [x]  Design Forget password Screen
- [x] Design a Drawer Navigation Menu 

## Note 
Complete a design and then submit it for peer review. Do not submit the whole design in once.

**Comment by DemiAdisa** [comment]
The issue has been completed, Please take a look at the prototype [here](https://www.figma.com/proto/3714aYKYor5Sll85z8yuqm/MindjoggUI?node-id=2%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2)
